### ISSUE TITLE
Last activity as date

### ISSUE THREAD

**Issue by Chucky2401** [joyrider3774/Playnite_html_exporter#3]
Hi,
I discovered the app Playnite and your plugin very soon, and I love it!

I would like to know if it is possible to modify the last activity column by a short date instead of "Yesterday" or "Last month"?

Thank you!

**Comment by joyrider3774** [comment]
use "lastactivitydate" and "lastactivitytime" in the templates (make a copy of the template and adapt as you wish) or modify the templates, i think i had added a safety check so it does not overwrite existing files upon new releases or i i gave preference to templates existing in the userdata folder instead of the addon installation folder (try both, preferably copying the templates to user data folder of the plugin if they are not there yet)
