### ISSUE TITLE
Minor HTML table formatting error in template

### ISSUE THREAD

**Issue by luxzg** [joyrider3774/Playnite_html_exporter#6]
At least in this one template that I use (didn't check others) there's HTML error/typo.

File is:
`Playnite_html_exporter/templates/default list text/page.txt`

It says:
`<COL WIDTH="width="13%">`

Should be:
`<COL WIDTH="13%">`

**Comment by luxzg** [comment]
Also multiple typos with:
`<COL WIDHT="10%">`

instead

`<COL WIDTH="10%">`

(widHT vs widTH)

**Comment by joyrider3774** [comment]
yeah was aware of this someone already reported it i also made such mistakes in the css, i think that happens when your not native english speaker :) i'll get around to fixing those eventually but need to check if it does not cause weird behaviour all of a sudden when i actually fix those and did not had the time yet
