### ISSUE TITLE
Index file doesn't generate if first page is grouped by something other than "Name"

### ISSUE THREAD

**Issue by qwirksilver** [joyrider3774/Playnite_html_exporter#7]
## Steps to reproduce
1. In the add-on settings, highlight page 1 and change the "Group field" to anything other than "Name." (I reproduced by selecting Platform, Genre, and Feature - I didn't test more than those.)
2. Generate the HTML site.

## Expected
- An index.html file should be generated in the export folder.

## Actual
- The index.html file is missing from the export folder.

## Notes 
- There are a few people in [this thread](https://www.playnite.link/forum/thread-664.html)reporting a missing index file.

**Comment by joyrider3774** [comment]
Yes there was such bug i have fixed it, from now on the very first page will always be named "index.html" instead of the page with name groupfield. If people had removed pages with the name groupfield it would fail to create an index.html in previous versions (be aware i have not released a new plugin version yet)
